trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: npm install -g snyk
    displayName: 'Install Snyk CLI'

  - script: snyk config environment SNYK-US-02
    displayName: 'Set Snyk region'

  - script: snyk auth $(SNYK_TOKEN)
    displayName: 'Authenticate Snyk'
    env:
      SNYK_TOKEN: $(SNYK_TOKEN)

  - script: snyk code test
    displayName: 'Run Snyk Code (SAST) Test'
    continueOnError: true

  - script: snyk test
    displayName: 'Run Snyk Open Source Test'
    continueOnError: true