name: Snyk CLI Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Set Snyk region
        run: snyk config environment SNYK-US-02

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Run Snyk Code (SAST) Test
        run: snyk code test
        continue-on-error: true

      - name: Run Snyk Open Source Test
        run: snyk test
        continue-on-error: true
